apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cdn.example
      secretName: astra-cdn-edge-tls
  rules:
    - host: cdn.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edge
                port:
                  number: 80
