apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: astra-cdn
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - origin-assets-pvc.yaml
  - example-origin.yaml
  - edge.yaml
  - control.yaml
  - inference.yaml
  - dashboard.yaml
