FROM docker.io/library/golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod ./
COPY go.sum ./
COPY services/control ./services/control
RUN go build -o /out/control ./services/control/cmd/control

FROM docker.io/library/alpine:3.20
RUN adduser -D -H astracdn
USER astracdn
COPY --from=build /out/control /usr/local/bin/control
EXPOSE 8081
ENTRYPOINT ["/usr/local/bin/control"]
